# Generated by Django 4.2.7 on 2023-12-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('Product', '0003_alter_category_parent_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Payment.itempaymentinfo'),
        ),
    ]
