# Generated by Django 4.2.7 on 2023-12-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='Product.product'),
        ),
    ]
