# Generated by Django 4.2.7 on 2023-12-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_propertyvalue_product'),
        ('Cart', '0002_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='Product.product'),
        ),
    ]
